defaults:
  - _self_
  - /output: default_output
  - /dataset: default_dataset
  - /model: default_model

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${dataset.type}_${dataset.name}_${dataset.recording}_${now:%Y-%m-%d}/${now:%H-%M-%S}
  