defaults:
  - _self_
  - /output: default_output
  - /dataset: default_dataset
  - /model: default_model

experiment: sandbox

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${dataset.type}_experiments/experiment_${experiment}/single/interp_${model.dictionary.num_elements}_${model.cdl.interpolate}/seed_${dataset.gen.seed}
  sweep:
    dir: ./outputs/${dataset.type}_experiments/experiment_${experiment}/multi
    subdir: interp_${model.dictionary.num_elements}_${model.cdl.interpolate}/seed_${dataset.gen.seed}