type: spikeforest # dataset type
name:  paired_mea64c # dataset name (only one used in practice)
recording: "20170622_patch2" # recording name (only one used in practice)
uri: sha1://1d343ed7e876ffd73bd8e0daf3b8a2c4265b783c?spikeforest-recordings.json # uri used to download the recording with spikeforest

tstart_s: 0 # Start time of the training recording (recording on which the dictionary is learnt)
tstop_s: 100 # Stop time of the training recording

tstart_test_s: 10 # Start time of the test recording (recording used to test events detection, with a fixed dictionary)
tstop_test_s: 12  # Stop time of the test recording

channel: 18 # Channel to use for training and testing
detect_threshold: 10 # Threshold for peak detection. Used to initialize the dictionaries in "real" mode.

preprocess: true # Whether to apply preprocessing for "spikeforest" dataset
preprocess_params: # Parameters for preprocessing
  freq_min: 300
  freq_max: 6000

window: # Parameters for setting windows (or segments) around events
  split: true # Whether to split into windows
  window_size_s: 0.0044 # Size of the windows (in seconds)

gen:
  seed: # Only used for synthetic data