type: spikeforest
name:  paired_mea64c
recording: "20170622_patch2"
uri: sha1://1d343ed7e876ffd73bd8e0daf3b8a2c4265b783c?spikeforest-recordings.json

tstart_s: 0
tstop_s: 100 # 250

tstart_test_s: 250
tstop_test_s: 255

channel: 18 #0
detect_threshold: 5 #10

preprocess: true
preprocess_params:
  freq_min: 300
  freq_max: 6000

window:
  split: true
  window_size_s: 0.0044

gen:
  seed: # Only used for synthetic data