# See default_dataset.yaml for more information
type: synth
name:  synthetic
recording: synthetic
uri:

tstart_s:
tstop_s:
duration_s:

tstart_test_s:
tstop_test_s:

channel: 0
detect_threshold: 5

preprocess: false
preprocess_params:
  freq_min:
  freq_max:

window:
  split: true
  window_size_s: 0.015


# Synth-specific parameters
sources:
  num: 2 # number of sources
  length_ms: 10.125 # length of each unit in ms

gen:
  seed: # Seed used for random number generation
  noise: 0.1 # Standard deviation of the added Gaussian noise
  amps: [1, 2] # Amplitudes of the unit sources vary within this range
  numOfEvents: 10 # Number of events per unit source
  T: 3 # Duration of the signals (training and test) in seconds

fs: 8000 # Sampling frequency