type: synth
name:  synthetic
recording: synthetic
uri:

tstart_s:
tstop_s:
duration_s:

tstart_test_s:
tstop_test_s:

channel: 0

preprocess: false
preprocess_params:
  freq_min:
  freq_max:

window:
  split: true
  window_size_s: 0.03


# Synth-specific parameters
sources:
  num: 2
  length_ms: 10.5

gen:
  seed:
  noise: 0.1
  amps: [1, 2]
  numOfEvents: 10
  T: 3

fs: 10000