type: synth
name:  synthetic
recording: synthetic
uri:

tstart_s:
tstop_s:
duration_s:

channel: 0

preprocess: true
preprocess_params:
  freq_min: 300
  freq_max: 6000

window:
  split: false
  window_size_s: 0.044


# Synth-specific parameters
sources:
  num: 2
  length_ms: 11

gen:
  noise: 0.1
  amps: [1, 2]
  numOfEvents: 20
  T: 5

fs: 3000