dictionary:
  num_elements: 1
  element_length_ms: 2.15 # should make an odd number of samples # 2.3
  init_templates: "real" # "real" "random" "signal"

cdl:
  num_iterations: 15
  interpolate: 0 # should be even, 0 means no interpolation
  sparsity_tol: 1
  error_tol: 0.01