# See default_model.yaml for more information
dictionary:
  num_elements: 2
  element_length_ms: 2.15 
  init_templates: "cluster"

cdl:
  num_iterations: 20
  interpolate: 10 
  sparsity_tol: 1
  sparsity_tol_test: 60
  rel_amp_split_test: 0.4
  error_tol: 0.01
  interpolator_type: sinc