dictionary:
  num_elements: 2 # 1
  element_length_ms: 2.15 # should make an odd number of samples
  init_templates: "cluster" # "real" "random" "signal"

cdl:
  num_iterations: 20
  interpolate: 10 # should be even, 0 means no interpolation
  sparsity_tol: 1
  sparsity_tol_test: 60 # base it on the number of spikes in the test data OR a criteria on matching (amplitude not too high or low)
  rel_amp_split_test: 0.4
  error_tol: 0.01
  interpolator_type: sinc