# See default_model.yaml for more information
defaults:
  - default_model
  - _self_

dictionary:
  num_elements: 2
  element_length_ms: 10.125
  init_templates: "real_noisy"
  real_random_noise: 0.2

cdl:
  num_iterations: 10
  interpolate: 10
  sparsity_tol: 1
  sparsity_tol_test: 25
  rel_amp_split_test: 0.6
  error_tol: 0.01
  interpolator_type: sinc
  permute_templates: false