dictionary:
  num_elements: 2
  element_length_ms: 11 # should make an odd number of samples # 2.3
  init_templates: "signal" # "real" "random" "signal"

cdl:
  num_iterations: 5
  interpolate: 0 # should be even, 0 means no interpolation
  sparsity_tol: 1
  error_tol: 0.01